### ISSUE TITLE
Cannot get the parse to work

### ISSUE THREAD

**Issue by pkankipati** [chainpoint/chainpoint-parse#2]
Hi
I'm using the app to use chainpoint parse method and keeps getting errors. I'm following the example on the readme, ie the chainpoint object is sent with a valid Proof (btc anchored).
Error is not descriptive.. I need to get both block height and the btc txId.

ERROR:
Error: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
    at Object.parse (/Users/anilakankipati/pad/conf/writeToBitcoinchain/js/node_modules/chainpoint-parse/index.js:26:33)
    at allJSONs.forEach.entry (/Users/anilakankipati/pad/conf/writeToBitcoinchain/js/checkChaincode.js:20:38)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/anilakankipati/pad/conf/writeToBitcoinchain/js/checkChaincode.js:17:10)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)

here's the simple code

    try {
        let chainpointProofObject = {proof: entry.proof};
        let result = chainpointParse.parse(chainpointProofObject);
        console.log(result);
    } catch (error) {
        console.log('error occured: ' + error.message);
        console.log(error);
    }

entry:
{
    "name": "<NAME>",
    "email": "<name>@xxxxx",
    "description": "This is to certify that <NAME> has successfully completed Blockchain hands−on programming workshop building a private blockchain on the 5th day of September 2018 at the BlockchainConf.tech. Presented by ...",
    "hash": "2a606c9a4e7f47af876ba80eea665058ff5630c424203970b23b24a5fd05d5ea",
    "hash_id_node": "5efdf690-b3d8-11e8-b1b5-0150c9747fb5",
    "proof": "eJyVVstuJUYRhT/gI1iheFxd/fZqJHaIJatsrHp0YUuDbdk3EJaBDUvyCZCBSSI2SIgl/2HEx3DadmY09kUKV17YfV2nq6vOOVV/+Pq1XV8d1ueHf10cDjd3Z6env8mX/ur69pendiGXVzfXl1eH01/nt4ff3qxvf/r+6O2F3F3cv2Zp1GxKWT1Klxi9qQxaS1qrVEdEbZmscGHKs5NyVi5Sw6l6XfK3DXN+6edX177uf1xXeLRJJ5p9nKS0xokmrSeUKtnspYfWfz6E3H2mv7o8HNZj5Lkc/sGUxglN/PyC+CzTWeVP38Pb9S3gG+Uenj+CL0M2vGderS/Lz+F35HH48unXeitXdrHuvvz9X96Irjd/N3lzvo+ub88fv/vq+ubuPz/40Rd/enP/yUOml372fV75xZ+vb97dXcgJ17aDX4e2oJaHIdrEVdag1KSP0gZTDLJFqxvnkks1U7VBs+c6IyZxHi8AszDpGlPrGmnRVK8uuaFLNXmvPNDCEnXYqqlzobC1VlKdUVpmzh8D3t6/nq1zbstXCM1Z2XsP4lrC1+LZZ+Jku+ejrVRwdSSh1az2Yoyo9DzDTx5Kj3p9n7Y9D/7j1eXd4SzV3EojJjpT4SoIaDzryCza61KznsRLcfxJiwgPBWNJuKHOc5XRfPM3q2uboSvvkggrz+ECHmeh4atU2rTmjopOjhFdVaQOWdlaisUO3OcJThAq0ajvc2z49ew7EcqrD+rbYjwDsc6eIh6K7QwSuVJmklmidfKZ+0hjEPUYZWrOyaAzyTNRRnlR47rQXPaBHn+UzrtHyoLGDzL/Cpd988TiS3/3dO3bz24v7768f/W/UjxF1LpyuT19CjjdSvogkd89SUQPdkwiP3l4lnJdq8/MM9eGqptOH5Zb5C4VrOOcLSSJ2Awfsy82G9qWNu6J8JQXpEyFUV6XlsrIWjLVmUHkSMOjrH0yQYQi6GONSApu2BylDKrFyF/IhqjpkKDRMrqvHa0Fh2eHghElPAAAw4OiwBXIadQUraXsGU3qZi8ytFnags40CX6pWzWJCrjHW0uowJoNt8mc3NvW6a7PBpQxFBe9AHSTUdly9NSSBFTOA/x1DVacBTvBLBKCwc3QYjWvaHkhedsFfwGYa+5FLLXZgAhjyGNUEeFMA5beRPBWcVgHcisqu7B99QRpwaSeZ4gaWkOfiRlFRw7NZKYE+RC0JeTOztR8phjZjFvLSRKUVSo0UnDNegb47x/+jBI9ftIg7mVu1iBdypZnA05E5j2ZFOSP1DWKdCRtAcnMoO7mKaoFTOAJqcFiMm1pM06UKqZcmqRlNs+5JPUY8OEuyeC73QJ3QI3NQTcaRaOWBXtVMCGhocxUrLfcK9rTjFTVLedKEYZ3wS1q7amodvStljKlxZwzdUInSeFKTjDQfcOshiplo4DQaWAEo30N9eYO1jiunWhEjAbmzJJZoRMro87GIZjIj59tih9/GGkw7Y7/3Cw7Sv7+X9LsIGAqM1IU2u3vupZ7LmZVZQZCbdufUfGa5hhi38XuZn371KyTz/mBUTBID3glGN0xpCRFdsdTwL8QmBo4VBeHouBoZ8dzRgUxUh954Pt2DBMsmQ46DkTiuIPwOlahZZhiySEmhzuy1bES5qOniefWlHQx+BvxAhNETXgqYHbvHBNoIY0oPlFaeG4W+IbmlVNxeBImkcJkMNQUdeaRQu0YJrQdJE4zO8qwVovuMVG4UmHTjnELpjZ4nkjMsAQHNJMyYQYZHvLy7cCE6tbCklUKiNpHzSVsgsml4HEFc8GDYRVoH9S0tlE1IDbBaIZyWY5hNiwGIFDyKuAgNjvMvRD4LAo2kSKyhowXae1kzj1qb8MRoJ0nVr9jmNseFKNIR+SMlsPiLQrmKTw88/Y9ZevLlRXTDCOrDVj19DJtzVgv67ntrjs5NAQ7sbKGjQIDnwbJ4BZDdh2XYtBDx82wfGaNbf0pY1BuNh3DJM3hEG6qvbZtKcO2hKiXshcsa9gLRvLhHTbcodmOpUsWWoiksaAdw4RpM+S8TKXSQp9GKwsMKgSPgQGWVmGW4AQwXPsaMDuW2vEqLFazHNUR3gyS7DmwIA7B9rJY4W4xsX0ozcF7q+sQI04ci4k37IgBW4NpHOE8MBe+XWTsCwQ0EAQrKbajKXBUq9KlMLiOBS5NCA0OirlR2DM0weqlPsd8vlxg/n9YLv5a8fxR/r/dAvI+dTnIfwGp5/4C",
    "anchors_complete": [
      "cal",
      "btc"
    ]
  },

**Comment by miketwenty1** [comment]
Using the example code in the README.md I am able to parse the above proof.

This is my app.js
```
const chainpointParse = require('chainpoint-parse')

// Valid proof in JS Object, Buffer, Hex String, or Base64 String form
let chainpointProofObject = "eJyVVstuJUYRhT/gI1iheFxd/fZqJHaIJatsrHp0YUuDbdk3EJaBDUvyCZCBSSI2SIgl/2HEx3DadmY09kUKV17YfV2nq6vOOVV/+Pq1XV8d1ueHf10cDjd3Z6env8mX/ur69pendiGXVzfXl1eH01/nt4ff3qxvf/r+6O2F3F3cv2Zp1GxKWT1Klxi9qQxaS1qrVEdEbZmscGHKs5NyVi5Sw6l6XfK3DXN+6edX177uf1xXeLRJJ5p9nKS0xokmrSeUKtnspYfWfz6E3H2mv7o8HNZj5Lkc/sGUxglN/PyC+CzTWeVP38Pb9S3gG+Uenj+CL0M2vGderS/Lz+F35HH48unXeitXdrHuvvz9X96Irjd/N3lzvo+ub88fv/vq+ubuPz/40Rd/enP/yUOml372fV75xZ+vb97dXcgJ17aDX4e2oJaHIdrEVdag1KSP0gZTDLJFqxvnkks1U7VBs+c6IyZxHi8AszDpGlPrGmnRVK8uuaFLNXmvPNDCEnXYqqlzobC1VlKdUVpmzh8D3t6/nq1zbstXCM1Z2XsP4lrC1+LZZ+Jku+ejrVRwdSSh1az2Yoyo9DzDTx5Kj3p9n7Y9D/7j1eXd4SzV3EojJjpT4SoIaDzryCza61KznsRLcfxJiwgPBWNJuKHOc5XRfPM3q2uboSvvkggrz+ECHmeh4atU2rTmjopOjhFdVaQOWdlaisUO3OcJThAq0ajvc2z49ew7EcqrD+rbYjwDsc6eIh6K7QwSuVJmklmidfKZ+0hjEPUYZWrOyaAzyTNRRnlR47rQXPaBHn+UzrtHyoLGDzL/Cpd988TiS3/3dO3bz24v7768f/W/UjxF1LpyuT19CjjdSvogkd89SUQPdkwiP3l4lnJdq8/MM9eGqptOH5Zb5C4VrOOcLSSJ2Awfsy82G9qWNu6J8JQXpEyFUV6XlsrIWjLVmUHkSMOjrH0yQYQi6GONSApu2BylDKrFyF/IhqjpkKDRMrqvHa0Fh2eHghElPAAAw4OiwBXIadQUraXsGU3qZi8ytFnags40CX6pWzWJCrjHW0uowJoNt8mc3NvW6a7PBpQxFBe9AHSTUdly9NSSBFTOA/x1DVacBTvBLBKCwc3QYjWvaHkhedsFfwGYa+5FLLXZgAhjyGNUEeFMA5beRPBWcVgHcisqu7B99QRpwaSeZ4gaWkOfiRlFRw7NZKYE+RC0JeTOztR8phjZjFvLSRKUVSo0UnDNegb47x/+jBI9ftIg7mVu1iBdypZnA05E5j2ZFOSP1DWKdCRtAcnMoO7mKaoFTOAJqcFiMm1pM06UKqZcmqRlNs+5JPUY8OEuyeC73QJ3QI3NQTcaRaOWBXtVMCGhocxUrLfcK9rTjFTVLedKEYZ3wS1q7amodvStljKlxZwzdUInSeFKTjDQfcOshiplo4DQaWAEo30N9eYO1jiunWhEjAbmzJJZoRMro87GIZjIj59tih9/GGkw7Y7/3Cw7Sv7+X9LsIGAqM1IU2u3vupZ7LmZVZQZCbdufUfGa5hhi38XuZn371KyTz/mBUTBID3glGN0xpCRFdsdTwL8QmBo4VBeHouBoZ8dzRgUxUh954Pt2DBMsmQ46DkTiuIPwOlahZZhiySEmhzuy1bES5qOniefWlHQx+BvxAhNETXgqYHbvHBNoIY0oPlFaeG4W+IbmlVNxeBImkcJkMNQUdeaRQu0YJrQdJE4zO8qwVovuMVG4UmHTjnELpjZ4nkjMsAQHNJMyYQYZHvLy7cCE6tbCklUKiNpHzSVsgsml4HEFc8GDYRVoH9S0tlE1IDbBaIZyWY5hNiwGIFDyKuAgNjvMvRD4LAo2kSKyhowXae1kzj1qb8MRoJ0nVr9jmNseFKNIR+SMlsPiLQrmKTw88/Y9ZevLlRXTDCOrDVj19DJtzVgv67ntrjs5NAQ7sbKGjQIDnwbJ4BZDdh2XYtBDx82wfGaNbf0pY1BuNh3DJM3hEG6qvbZtKcO2hKiXshcsa9gLRvLhHTbcodmOpUsWWoiksaAdw4RpM+S8TKXSQp9GKwsMKgSPgQGWVmGW4AQwXPsaMDuW2vEqLFazHNUR3gyS7DmwIA7B9rJY4W4xsX0ozcF7q+sQI04ci4k37IgBW4NpHOE8MBe+XWTsCwQ0EAQrKbajKXBUq9KlMLiOBS5NCA0OirlR2DM0weqlPsd8vlxg/n9YLv5a8fxR/r/dAvI+dTnIfwGp5/4C";

try {
  let result = chainpointParse.parse(chainpointProofObject)
  console.log(JSON.stringify(result));
} catch (error) {
  console.error(`An error has occurred: ${error.message}`)
}
```
You can do an `npm init` followed by a `npm install --save chainpoint-parse`
Then you can run something like this `node app.js | jq`
I get this 
```
{
  "hash": "2a606c9a4e7f47af876ba80eea665058ff5630c424203970b23b24a5fd05d5ea",
  "hash_id_node": "5efdf690-b3d8-11e8-b1b5-0150c9747fb5",
  "hash_submitted_node_at": "2018-09-09T02:30:52Z",
  "hash_id_core": "6037fd30-b3d8-11e8-b48a-015d32e67ec3",
  "hash_submitted_core_at": "2018-09-09T02:30:54Z",
  "branches": [
    {
      "label": "cal_anchor_branch",
      "anchors": [
        {
          "type": "cal",
          "anchor_id": "2011085",
          "uris": [
            "https://a.chainpoint.org/calendar/2011085/hash"
          ],
          "expected_value": "c51e2f2b3205f604766d72a815a9b1114602333cecc02fe716f8b3bf35311336"
        }
      ],
      "branches": [
        {
          "label": "btc_anchor_branch",
          "anchors": [
            {
              "type": "btc",
              "anchor_id": "540584",
              "uris": [
                "https://a.chainpoint.org/calendar/2011225/data"
              ],
              "expected_value": "562ed735da8114c31501af9db533da5f36a999c635fab54fa25ac5a835345dae"
            }
          ],
          "opReturnValue": "91513875dfc2d69a8fb20aa3e215cfec79fcf8e9e51758fd4e9599a402656a06",
          "btcTxId": "ebe7adeb7423a1ea8ca95a73ff050ed38a75daf040035c484fb80404ba5cecf2"
        }
      ]
    }
  ]
}
```
You can see here that the Transaction associated with this btc anchor has a tx-id of:
`ebe7adeb7423a1ea8ca95a73ff050ed38a75daf040035c484fb80404ba5cecf2`
https://www.blockchain.com/btc/tx/ebe7adeb7423a1ea8ca95a73ff050ed38a75daf040035c484fb80404ba5cecf2

**Comment by grempe** [comment]
I believe @miketwenty1 provided the info you needed to resolve this issue. I'll close it for now. Please ping us if you need further assistance.

Cheers.
